/**
 * @overview generated by ghoti-cli
 * @fileoverview Router
 */

import * as React from 'react';
import * as Components from './components/import';

class Hello extends React.Component<{}, {}> {
    public constructor(props) {
        super(props);
    }

    public render() {
        return (
            <React.Fragment>
                <Components.Container>
                    Container Exmaple
                </Components.Container>
                <Components.Paper title="paper">
                    Paper example
                    <Components.Button>
                        123
                    </Components.Button>
                </Components.Paper >
                <Components.Paper title="Button Group">
                    <Components.Flex>
                        <Components.Button flex={1} style={{
                            margin: '3px',
                        }}>
                            BUTTON1
                        </Components.Button>
                        <Components.Button flex={2} style={{
                            margin: '3px',
                        }}>
                            BUTTON2
                        </Components.Button>
                    </Components.Flex>
                    <Components.Flex>
                        <Components.Button flex={1} style={{
                            margin: '3px',
                        }}>
                            BUTTON1
                        </Components.Button>
                        <Components.Button flex={1} style={{
                            margin: '3px',
                        }}>
                            BUTTON2
                        </Components.Button>
                    </Components.Flex>
                </Components.Paper >
                <Components.Paper title="DARK SIDE">
                    <Components.Button dark>
                        DARKBUTTON
                    </Components.Button>
                    <Components.Button dark disabled>
                        DISABLED
                    </Components.Button>
                </Components.Paper >
            </React.Fragment>
        );
    }
}

export default Hello;
